version: '3.8'

services:
  devcontainer:
    image: harachin/devcontainer-base:1.0.0
    tty: true
    volumes:
      - .:/workspace

  api:
    build:
      context: .
    tty: true
    volumes:
      - .:/api
